version: "3"

services:
  etracs-server:
    container_name: etracs-server
    image: ramesesinc/etracs-server-province:2.5.04.01.01
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports:
      - "8060:8060"
      - "8061:8061"
      - "8070:8070"
    volumes:
      - ./modules:/apps/etracs25/modules

      - ../../_custom/datasources:/services/datasources
      - ../../_res/connections:/apps/etracs25/connections/ext
      - ../../_custom/module-server:/apps/etracs25/modules/ext/zzz-lgu-custom-module

      - ../../_custom/output:/apps/server/output
      - ../../_custom/fileserver:/fileserver

      ## temporarily mounting a blank folder to disable old sync services
      - ./blank:/services/modules/rptis/rameses-gov-etracs-rptis-sync-services.jar

      - ./dev_libs/rameses-osiris3-rules.jar:/apps/server/lib/rameses-osiris3-rules.jar
      - ./dev_modules/rules:/services/modules/rules
      - ./dev_modules/treasury:/services/modules/treasury
      - ./dev_modules/etracs:/services/modules/etracs
      - ./dev_modules/enterprise:/services/modules/enterprise
      - ./dev_modules/entity:/services/modules/entity
