version: "3"

services:

   etracs-server:
      volumes:
         - ./dev-modules/rptis/rameses-gov-etracs-rptis-landtax-report-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-landtax-report-services.jar
         - ./dev_modules/rules:/services/modules/rules
