version: "3"

services:

   etracs-server:
      volumes:
         ## this is only a seed mapping, please do not remove
         ## 
         - ../../_custom/.emptydir:/.emptydir

         ## temporarily mounting a blank folder to disable old sync services
         ## 
         - ./blank:/services/modules/rptis/rameses-gov-etracs-rptis-sync-services.jar
