version: "3"

services:

   etracs-server:
      volumes:
         - ./dev_modules/rules:/services/modules/rules
         - ./dev_modules/admin:/services/modules/admin
         - ./dev_modules/treasury:/services/modules/treasury

         - ./dev_modules/rptis/rameses-gov-etracs-rptis-sync2-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-sync2-services.jar
