version: "3"

services:
  etracs-server:
    volumes:
      ## temporarily mounting of dev-modules
      - ./dev-modules/rptis/rameses-gov-etracs-rptis-report-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-report-services.jar